# Generated by Django 2.1.15 on 2022-01-03 12:07

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cpu_speed',
            field=models.FloatField(blank=True, max_length=100, null=True, validators=[inventory.models.validate_decimals_cpu_speed]),
        ),
        migrations.AlterField(
            model_name='device',
            name='monitor_make',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='monitor_size',
            field=models.FloatField(blank=True, null=True, validators=[inventory.models.validate_decimals_monitor_size]),
        ),
    ]
