# Generated by Django 3.2.8 on 2021-12-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_device_gin_iqar_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='poNumber',
        ),
    ]
