# Generated by Django 2.1.15 on 2022-01-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220103_1737'),
        ('inventory', '0003_delete_ponumber'),
    ]

    operations = [
    ]
