# Generated by Django 2.1.15 on 2022-01-07 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_merge_20220104_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 7), null=True),
        ),
    ]
