# Generated by Django 2.1.15 on 2022-01-28 10:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20220107_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='po_srno',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='PO Number : Serial Number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 28), null=True),
        ),
    ]
