# Generated by Django 3.2 on 2022-02-11 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20220128_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 11), null=True),
        ),
    ]
