# Generated by Django 3.2 on 2022-02-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20220220_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='allocation_status',
            field=models.CharField(choices=[('IQC', 'IQC'), ('Allocated', 'Allocated'), ('Decommissioned', 'Decommissioned'), ('Free', 'Free'), ('Needs Maintainence', 'Needs Maintainence'), ('Repair/Replace', 'Repair/Replace')], default='IQC', max_length=20),
        ),
    ]
