# Generated by Django 3.2 on 2022-03-03 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_device_allocation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 3), null=True),
        ),
    ]
