# Generated by Django 3.2 on 2022-03-29 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_device_warranty_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='details',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 29), null=True),
        ),
    ]
