# Generated by Django 3.2 on 2022-03-29 10:43

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20220329_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemname',
            name='item_category',
            field=models.CharField(choices=[('IT', 'IT'), ('Hardware', 'Hardware'), ('Administration', 'Administration')], default='IT', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True, validators=[inventory.models.project_status_validator]),
        ),
    ]
